# -*- coding: utf-8 -*-
"""FP-IR-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Fn4mXV7wiTVpZp6n-mDlJESTm3W7oe4
"""

# ============================================================
#%% 📦 CELL 1 — Install Dependencies
# ============================================================

import subprocess, sys

def run(cmd):
    subprocess.run(cmd, shell=True, check=True)

run("pip install -q open_clip_torch>=2.20.0")

# ── PyTorch 2.6 fix: allowlist numpy globals for torch.load ──
import torch
import numpy as np
torch.serialization.add_safe_globals([
    np.core.multiarray.scalar,
    np.dtype,
    np.ndarray,
])
print("✅ PyTorch safe globals registered (numpy compat)")

run("pip install -q transformers>=4.35.0")
run("pip install -q timm>=0.9.0")
run("pip install -q sentence-transformers>=2.2.0")
run("pip install -q pyarrow>=12.0.0 pandas numpy pillow tqdm scikit-learn scipy pyyaml")

print("✅ Dependencies installed")

# Commented out IPython magic to ensure Python compatibility.
import kagglehub
from google.colab import userdata
username = userdata.get('KAGGLE_USERNAME')
key = userdata.get('KAGGLE_KEY')
# %env KAGGLE_USERNAME=$username
# %env KAGGLE_KEY=$key

!sudo apt install aria2 -y

!aria2c -x 16 -s 16 -k 1M \
--http-user=$KAGGLE_USERNAME \
--http-passwd=$KAGGLE_KEY \
--continue=true \
--max-connection-per-server=16 \
--split=16 \
--min-split-size=10M \
-o sch-datasets.zip \
"https://www.kaggle.com/api/v1/datasets/download/farhanwew/minecraft-schematics-mvm"

!unzip -q sch-datasets.zip -d data

# ============================================================
#%% 📁 CELL 2 — Clone mc-retrieval (untuk PointBERT code + weights)
# ============================================================

import os

REPO_DIR = "/content/mc-retrieval"

if not os.path.exists(REPO_DIR):
    run(f"git clone https://github.com/information-retrieval-4/mc-retrieval.git {REPO_DIR}")
    print("✅ mc-retrieval cloned")
else:
    print("✅ mc-retrieval already exists")

# Add src to path agar bisa import PointBERT components
sys.path.insert(0, os.path.join(REPO_DIR, "src"))

# Download Point-BERT pretrained weights
CKPT_DIR = os.path.join(REPO_DIR, "checkpoints")
PB_WEIGHTS = os.path.join(CKPT_DIR, "Point-BERT.pth")
os.makedirs(CKPT_DIR, exist_ok=True)

if not os.path.exists(PB_WEIGHTS):
    print("Downloading Point-BERT.pth ...")
    run(f'wget "https://cloud.tsinghua.edu.cn/f/202b29805eea45d7be92/?dl=1" -O {PB_WEIGHTS}')
    print("✅ Point-BERT.pth downloaded")
else:
    print(f"✅ Point-BERT.pth already at {PB_WEIGHTS}")

# ── ATUR PATH DI SINI ─────────────────────────────────────────
PARQUET_PATH  = f"{REPO_DIR}/data/data_with_voxel_names_multiview_image.parquet"
RENDERS_BASE  = "/content/data/renders"   # folder berisi 000001_xxx/, 000002_xxx/, dst
SAVE_DIR      = f"{REPO_DIR}/checkpoints/trimodal_p6"

os.makedirs(SAVE_DIR, exist_ok=True)
print(f"Parquet : {PARQUET_PATH}")
print(f"Renders : {RENDERS_BASE}")
print(f"Save to : {SAVE_DIR}")

# ============================================================
#%% 🔧 CELL 4 — Config (Optimal dari Percobaan 6)
# ============================================================

CFG = {
    # ── Data ──────────────────────────────────────────────────
    "parquet_path"          : PARQUET_PATH,
    "renders_base"          : RENDERS_BASE,
    "text_mode"             : "cleaned_aug",   # cleaned + augmentasi
    "max_block_types"       : 672,             # name vocab (Strategy 1)
    "text_max_length"       : 77,
    "crop_bbox"             : True,
    "augment_voxel"         : True,
    "voxel_aug_prob"        : 0.5,
    "voxel_dropout_prob"    : 0.05,
    "val_split"             : 0.1,
    "test_split"            : 0.1,
    "seed"                  : 42,
    "n_views"               : 12,              # jumlah view per schematic
    "eval_view_idx"         : 6,               # view index saat evaluasi (frontal)

    # ── CLIP Image+Text Encoder ───────────────────────────────
    # openai/clip-vit-base-patch16 = public, no auth needed, output 512-dim
    # (TinyClip-39M private/gated → diganti dengan OpenAI CLIP yang equivalent)
    "tinyclip_hf_model"     : "openai/clip-vit-base-patch16",
    "use_hf_tinyclip"       : True,
    "freeze_clip"           : True,            # freeze CLIP backbone
    "clip_output_dim"       : 512,             # CLIP ViT-B/16 projection dim = 512
    "image_size"            : 224,

    # ── PointBERT (config optimal P6) ─────────────────────────
    "pb_pretrained_path"    : PB_WEIGHTS,
    "pb_freeze_backbone"    : False,           # ✅ UNFREEZE (P6 terbaik)
    "pb_trans_dim"          : 384,
    "pb_depth"              : 12,
    "pb_num_heads"          : 6,
    "pb_mlp_ratio"          : 4.0,
    "pb_drop_path"          : 0.1,
    "pb_num_points"         : 1024,
    "pb_block_embed_dim"    : 128,
    "pb_dropout"            : 0.1,
    "pb_use_fps_eval"       : True,
    "use_name_vocab"        : True,            # ✅ Strategy 1
    "use_semantic_init"     : True,            # ✅ Strategy 2

    # ── Shared Embedding ──────────────────────────────────────
    "embed_dim"             : 256,             # shared space dimensi

    # ── Training ──────────────────────────────────────────────
    "batch_size"            : 128,              # lebih kecil (3 modality)
    "epochs"                : 100,
    "temperature_init"      : 0.07,
    "warmup_ratio"          : 0.05,
    "early_stopping_patience": 15,
    "num_workers"           : 2,
    "use_amp"               : True,

    # ── Learning Rates (per param group) ──────────────────────
    # P6 optimal: unfreeze backbone dengan lr sangat kecil
    "lr_text_proj"          : 1e-4,            # TinyClip text projection head
    "lr_image_proj"         : 1e-4,            # TinyClip image projection head
    "lr_pb_adapter"         : 3e-4,            # PointBERT adapter layers
    "lr_pb_head"            : 1e-4,            # PointBERT output head
    "lr_pb_backbone"        : 5e-6,            # ✅ backbone unfreeze lr kecil
    "weight_decay"          : 1e-2,

    # ── Loss weights ──────────────────────────────────────────
    "lambda_ti"             : 1.0,             # Text ↔ Image
    "lambda_tv"             : 1.0,             # Text ↔ Voxel
    "lambda_iv"             : 1.0,             # Image ↔ Voxel

    # ── Eval ──────────────────────────────────────────────────
    "recall_k"              : [1, 5, 10],
    "checkpoint_dir"        : SAVE_DIR,
}

print("✅ Config loaded")
print(f"   embed_dim      = {CFG['embed_dim']}")
print(f"   batch_size     = {CFG['batch_size']}")
print(f"   freeze_clip    = {CFG['freeze_clip']}")
print(f"   freeze_pb      = {CFG['pb_freeze_backbone']}")
print(f"   use_name_vocab = {CFG['use_name_vocab']}")

# ============================================================
#%% 📚 CELL 5 — Imports
# ============================================================

import json
import re
import random
import math
import time
from collections import Counter
from pathlib import Path
from typing import Optional, List, Tuple, Dict

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR, LinearLR, SequentialLR
from torch.amp import autocast, GradScaler
from sklearn.model_selection import train_test_split
from scipy.ndimage import zoom
from PIL import Image
from tqdm import tqdm
from transformers import CLIPModel, CLIPProcessor

print("✅ All imports done")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"   Device: {DEVICE}")
if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
    print(f"   VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

# ============================================================
#%% 📝 CELL 6 — Text Preprocessing (sama dengan bimodal P6)
# ============================================================

def clean_text(text: str) -> str:
    """Strip HTML, normalize whitespace."""
    if not isinstance(text, str):
        return ""
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def build_text(row: pd.Series, text_mode: str = "cleaned_aug",
               top_k_materials: int = 5) -> str:
    """Build retrieval text string dari kolom dataset."""
    parts = []
    for field in ("title", "subtitle", "description"):
        val = row.get(field)
        if isinstance(val, str) and val.strip():
            parts.append(clean_text(val))

    tags = row.get("tags")
    if isinstance(tags, str):
        try:
            tag_list = json.loads(tags)
            if isinstance(tag_list, list):
                parts.append(", ".join(str(t) for t in tag_list))
        except Exception:
            parts.append(clean_text(tags))

    text = " ".join(parts)

    # ── Augmentasi teks (Strategy "cleaned_aug") ──────────────
    if text_mode == "cleaned_aug":
        vnd = row.get("voxel_name_data")
        if vnd is not None:
            try:
                names = list(vnd) if not isinstance(vnd, list) else vnd
                names = [n for n in names if isinstance(n, str) and "air" not in n]
                counter = Counter(names)
                top = [n.replace("minecraft:", "").replace("_", " ")
                       for n, _ in counter.most_common(top_k_materials)]
                if top:
                    text += " | materials: " + ", ".join(top)
            except Exception:
                pass

    return text.strip()

# ============================================================
#%% 🧊 CELL 7 — Voxel Preprocessing (sama dengan bimodal)
# ============================================================

def build_name_vocab(df: pd.DataFrame, max_types: int = 672):
    """Strategy 1: build block vocabulary dari nama string."""
    counter: Counter = Counter()
    for vnd in df["voxel_name_data"]:
        try:
            names = list(vnd) if not isinstance(vnd, list) else vnd
            counter.update(n for n in names if isinstance(n, str) and n != "minecraft:air")
        except Exception:
            pass
    # index 0=air, 1=<rare>, 2..N=frequent blocks
    top_blocks = [b for b, _ in counter.most_common(max_types - 2)]
    name2id = {"minecraft:air": 0, "<rare>": 1}
    for i, name in enumerate(top_blocks, start=2):
        name2id[name] = i
    id2name = {v: k for k, v in name2id.items()}
    return name2id, id2name


def remap_voxel_names(voxel_name_flat, name2id: dict,
                      crop_bbox: bool = True, target_size: int = 32) -> torch.LongTensor:
    """Convert nama block list → compact ID → 32³ tensor."""
    names = list(voxel_name_flat)
    arr = np.array([name2id.get(n, 1) for n in names], dtype=np.int64)
    vol = arr.reshape(32, 32, 32)

    if crop_bbox:
        non_air = vol != 0
        if non_air.any():
            coords = np.argwhere(non_air)
            mins = coords.min(axis=0)
            maxs = coords.max(axis=0) + 1
            cropped = vol[mins[0]:maxs[0], mins[1]:maxs[1], mins[2]:maxs[2]]
            shape = cropped.shape
            if all(s > 0 for s in shape):
                factors = (target_size / shape[0],
                           target_size / shape[1],
                           target_size / shape[2])
                vol = zoom(cropped.astype(np.float32), factors, order=0).astype(np.int64)
                vol = np.clip(vol, 0, None)

    return torch.from_numpy(vol.reshape(32, 32, 32)).long()


def augment_voxels(voxels: torch.LongTensor) -> torch.LongTensor:
    """Random 90° Y-axis rotations + horizontal flips (sama dengan P6)."""
    k = torch.randint(0, 4, (1,)).item()
    if k > 0:
        voxels = torch.rot90(voxels, k, dims=(1, 3))
    if torch.rand(1).item() > 0.5:
        voxels = voxels.flip(dims=(1,))
    if torch.rand(1).item() > 0.5:
        voxels = voxels.flip(dims=(3,))
    return voxels


def voxel_block_dropout(voxels: torch.LongTensor, p: float = 0.05) -> torch.LongTensor:
    """Randomly drop non-air blocks to 0 (augmentasi voxel)."""
    mask = (voxels != 0) & (torch.rand_like(voxels.float()) < p)
    return voxels.masked_fill(mask, 0)

# ============================================================
#%% 🖼️ CELL 8 — Image Path Resolution
# ============================================================

def resolve_image_path(row: pd.Series, renders_base: str,
                       view_idx: int = None, n_views: int = 12) -> Optional[str]:
    """
    Resolve path gambar dari row parquet.
    Handles kasus path di parquet berbeda dengan lokasi aktual.
    """
    if view_idx is None:
        view_idx = random.randint(0, n_views - 1)

    # Coba kolom view_XX_path langsung
    col = f"view_{view_idx:02d}_path"
    stored_path = row.get(col)

    if isinstance(stored_path, str) and stored_path:
        # Coba path langsung
        if os.path.exists(stored_path):
            return stored_path
        # Ambil basename folder + filename dan join dengan renders_base
        parts = Path(stored_path).parts
        if len(parts) >= 2:
            folder_name = parts[-2]
            file_name   = parts[-1]
            candidate = os.path.join(renders_base, folder_name, file_name)
            if os.path.exists(candidate):
                return candidate

    # Fallback: scan renders_base dengan render_folder kolom
    render_folder = row.get("render_folder")
    if isinstance(render_folder, str):
        candidate = os.path.join(renders_base, render_folder,
                                 f"view_{view_idx:02d}.jpg")
        if os.path.exists(candidate):
            return candidate

    return None  # image tidak ditemukan

# ============================================================
#%% 📊 CELL 9 — TriModal Dataset
# ============================================================

class TriModalDataset(Dataset):
    """
    Dataset yang mengembalikan (text, image_tensor, voxel_tensor, category) per item.

    Image loading:
      - train: random view dari 0–11
      - eval:  view_idx tetap (default view_06)
    """

    def __init__(self,
                 df: pd.DataFrame,
                 name2id: dict,
                 clip_processor: CLIPProcessor,
                 cfg: dict,
                 split: str = "train",
                 image_transform=None):
        self.df           = df.reset_index(drop=True)
        self.name2id      = name2id
        self.processor    = clip_processor
        self.cfg          = cfg
        self.split        = split
        self.is_train     = (split == "train")
        self.image_transform = image_transform

        # Pre-build text strings
        print(f"  [{split}] Building text strings ...")
        self.texts = [
            build_text(self.df.iloc[i], text_mode=cfg["text_mode"])
            for i in range(len(self.df))
        ]

        # Placeholder image (hitam) jika render tidak tersedia
        self.fallback_img = Image.new("RGB", (cfg["image_size"], cfg["image_size"]), (0, 0, 0))

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # ── Teks ─────────────────────────────────────────────
        text = self.texts[idx]

        # ── Image ─────────────────────────────────────────────
        if self.is_train:
            view_idx = random.randint(0, self.cfg["n_views"] - 1)
        else:
            view_idx = self.cfg["eval_view_idx"]

        img_path = resolve_image_path(row, self.cfg["renders_base"],
                                      view_idx=view_idx,
                                      n_views=self.cfg["n_views"])
        try:
            img = Image.open(img_path).convert("RGB") if img_path else self.fallback_img
        except Exception:
            img = self.fallback_img

        # CLIP processor handles resize + normalize
        pixel_values = self.processor(images=img, return_tensors="pt")["pixel_values"].squeeze(0)

        # ── Voxel ─────────────────────────────────────────────
        vnd = row.get("voxel_name_data")
        voxel = remap_voxel_names(vnd, self.name2id,
                                  crop_bbox=self.cfg["crop_bbox"])

        if self.is_train and self.cfg["augment_voxel"]:
            if random.random() < self.cfg["voxel_aug_prob"]:
                voxel = augment_voxels(voxel.unsqueeze(0)).squeeze(0)
            if random.random() < self.cfg["voxel_aug_prob"]:
                voxel = voxel_block_dropout(voxel, p=self.cfg["voxel_dropout_prob"])

        # ── Category ──────────────────────────────────────────
        category = str(row.get("subtitle", "Unknown"))

        return text, pixel_values, voxel, category


def collate_fn(batch):
    texts, images, voxels, categories = zip(*batch)
    images = torch.stack(images)
    voxels = torch.stack(voxels)
    return list(texts), images, voxels, list(categories)

# ============================================================
#%% 🔨 CELL 10 — Load Data & Build Dataloaders
# ============================================================

def load_dataset_and_build_loaders(cfg: dict):
    print("Loading parquet ...")
    df = pd.read_parquet(cfg["parquet_path"])
    print(f"  Total rows: {len(df)}")

    # Drop baris dengan voxel_name_data kosong
    df = df[df["voxel_name_data"].notna()].reset_index(drop=True)
    print(f"  After filtering: {len(df)}")

    # Build name vocab (Strategy 1)
    print("Building name vocabulary ...")
    name2id, id2name = build_name_vocab(df, max_types=cfg["max_block_types"])
    print(f"  Vocab size: {len(name2id)} block types")

    # Load TinyClip processor
    print(f"Loading TinyClip processor from {cfg['tinyclip_hf_model']} ...")
    processor = CLIPProcessor.from_pretrained(cfg["tinyclip_hf_model"])

    # Train / Val / Test split (stratified by subtitle)
    labels = df["subtitle"].fillna("Unknown").tolist()
    idx_all = list(range(len(df)))

    idx_train, idx_temp, _, labels_temp = train_test_split(
        idx_all, labels,
        test_size=cfg["val_split"] + cfg["test_split"],
        stratify=labels, random_state=cfg["seed"]
    )
    val_frac = cfg["val_split"] / (cfg["val_split"] + cfg["test_split"])
    idx_val, idx_test = train_test_split(
        idx_temp, test_size=1 - val_frac,
        stratify=labels_temp, random_state=cfg["seed"]
    )

    print(f"  Train: {len(idx_train)} | Val: {len(idx_val)} | Test: {len(idx_test)}")

    def make_loader(indices, split):
        ds = TriModalDataset(df.iloc[indices], name2id, processor, cfg, split=split)
        return DataLoader(
            ds, batch_size=cfg["batch_size"],
            shuffle=(split == "train"),
            num_workers=cfg["num_workers"],
            collate_fn=collate_fn,
            pin_memory=torch.cuda.is_available(),
            drop_last=(split == "train"),
        )

    train_loader = make_loader(idx_train, "train")
    val_loader   = make_loader(idx_val,   "val")
    test_loader  = make_loader(idx_test,  "test")

    return train_loader, val_loader, test_loader, name2id, id2name, processor

# ============================================================
#%% 🧠 CELL 11 — PointBERT Components (inline dari mc-retrieval)
# ============================================================

# ── FPS Sampling ──────────────────────────────────────────────

def fps_sample(xyz: np.ndarray, n_samples: int) -> np.ndarray:
    N = len(xyz)
    if N == 0:
        return np.zeros(n_samples, dtype=np.int64)
    if N <= n_samples:
        idx = np.arange(N)
        pad = np.random.choice(N, n_samples - N, replace=True)
        return np.concatenate([idx, pad])
    selected = np.zeros(n_samples, dtype=np.int64)
    dist = np.full(N, np.inf)
    farthest = np.random.randint(N)
    for i in range(n_samples):
        selected[i] = farthest
        d = np.sum((xyz - xyz[farthest]) ** 2, axis=1)
        dist = np.minimum(dist, d)
        farthest = int(np.argmax(dist))
    return selected


# ── VoxelToPoints ─────────────────────────────────────────────

class VoxelToPoints(nn.Module):
    """Konversi 32³ voxel grid → fixed-size point cloud (M points)."""

    def __init__(self, num_points: int = 512, use_fps_eval: bool = True):
        super().__init__()
        self.M = num_points
        self.use_fps_eval = use_fps_eval

    def _process_one(self, grid: torch.LongTensor, training: bool):
        device = grid.device
        M = self.M
        non_air = (grid != 0)
        coords = non_air.nonzero(as_tuple=False).float()  # (N, 3)
        bids   = grid[non_air]                            # (N,)
        N = coords.shape[0]

        if N == 0:
            return (torch.zeros(M, 3, device=device),
                    torch.zeros(M, dtype=torch.long, device=device))

        if N <= M:
            pad_idx = torch.randint(N, (M - N,), device=device)
            coords = torch.cat([coords, coords[pad_idx]], dim=0)
            bids   = torch.cat([bids,   bids[pad_idx]],   dim=0)
        elif training or not self.use_fps_eval:
            idx = torch.randperm(N, device=device)[:M]
            coords, bids = coords[idx], bids[idx]
        else:
            idx = fps_sample(coords.cpu().numpy(), M)
            idx = torch.from_numpy(idx).to(device)
            coords, bids = coords[idx], bids[idx]

        # Normalize to [0, 1]
        coords = coords / 31.0
        return coords, bids

    def forward(self, grids: torch.LongTensor):
        training = self.training
        B = grids.shape[0]
        all_xyz, all_bids = [], []
        for b in range(B):
            xyz, bids = self._process_one(grids[b], training)
            all_xyz.append(xyz)
            all_bids.append(bids)
        return torch.stack(all_xyz), torch.stack(all_bids)


# ── Transformer Building Blocks ───────────────────────────────

from timm.models.layers import DropPath, trunc_normal_

class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None,
                 act_layer=nn.GELU, drop=0.):
        super().__init__()
        hidden_features = hidden_features or in_features
        out_features    = out_features    or in_features
        self.fc1   = nn.Linear(in_features, hidden_features)
        self.act   = act_layer()
        self.fc2   = nn.Linear(hidden_features, out_features)
        self.drop  = nn.Dropout(drop)

    def forward(self, x):
        return self.drop(self.fc2(self.drop(self.act(self.fc1(x)))))


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        self.scale     = (dim // num_heads) ** -0.5
        self.qkv       = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj      = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv.unbind(0)
        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = self.attn_drop(attn.softmax(dim=-1))
        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        return self.proj_drop(self.proj(x))


class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False,
                 drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU):
        super().__init__()
        self.norm1     = nn.LayerNorm(dim)
        self.attn      = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias,
                                   attn_drop=attn_drop, proj_drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2     = nn.LayerNorm(dim)
        self.mlp       = Mlp(in_features=dim, hidden_features=int(dim * mlp_ratio),
                             act_layer=act_layer, drop=drop)

    def forward(self, x):
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


# ── PointBERT Encoder ─────────────────────────────────────────

class PointBERTVoxelEncoder(nn.Module):
    """
    Full PointBERT voxel encoder (inline, tidak perlu import mc-retrieval).

    Pipeline:
      (B, 32, 32, 32) LongTensor
      → VoxelToPoints  → (B, M, 3) coords + (B, M) block_ids
      → Embedding(vocab, block_embed_dim) → (B, M, block_embed_dim)
      → Concat [xyz | block_feats] → (B, M, 3+block_embed_dim)
      → input_proj Linear → (B, M, trans_dim)
      → 12-layer Transformer → (B, M, trans_dim)
      → Global avg pool → (B, trans_dim)
      → output_head → (B, embed_dim)
    """

    def __init__(self, cfg: dict, vocab_size: int):
        super().__init__()
        trans_dim       = cfg["pb_trans_dim"]
        block_embed_dim = cfg["pb_block_embed_dim"]

        self.voxel_to_pts = VoxelToPoints(
            num_points=cfg["pb_num_points"],
            use_fps_eval=cfg["pb_use_fps_eval"]
        )
        self.block_embedding = nn.Embedding(vocab_size, block_embed_dim)
        self.input_proj      = nn.Linear(3 + block_embed_dim, trans_dim)

        # Transformer blocks
        dpr = [x.item() for x in torch.linspace(0, cfg["pb_drop_path"], cfg["pb_depth"])]
        self.blocks = nn.ModuleList([
            Block(
                dim=trans_dim,
                num_heads=cfg["pb_num_heads"],
                mlp_ratio=cfg["pb_mlp_ratio"],
                qkv_bias=True,
                drop=cfg["pb_dropout"],
                attn_drop=0.,
                drop_path=dpr[i],
            ) for i in range(cfg["pb_depth"])
        ])
        self.norm = nn.LayerNorm(trans_dim)

        # CLS token (opsional, kita pakai avg pool saja)
        self.output_head = nn.Sequential(
            nn.Linear(trans_dim, cfg["embed_dim"]),
            nn.Dropout(cfg["pb_dropout"]),
        )

        self._init_weights()
        self._load_pretrained(cfg["pb_pretrained_path"])

        if cfg["pb_freeze_backbone"]:
            for p in self.blocks.parameters():
                p.requires_grad = False
            for p in self.norm.parameters():
                p.requires_grad = False
            print("  PointBERT backbone: FROZEN")
        else:
            print("  PointBERT backbone: TRAINABLE (lr=5e-6)")

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.LayerNorm):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)

    def _load_pretrained(self, path: str):
        if not path or not os.path.exists(path):
            print(f"  ⚠️  Point-BERT weights not found at {path}. Training from scratch.")
            return
        ckpt = torch.load(path, map_location="cpu", weights_only=False)
        state = ckpt.get("model", ckpt)
        # Filter keys yang cocok
        model_state = self.state_dict()
        matched, missing, unexpected = {}, [], []
        for k, v in state.items():
            k_stripped = k.replace("module.", "").replace("base_model.", "")
            # Map transformer key names dari original PointBERT
            if k_stripped in model_state and model_state[k_stripped].shape == v.shape:
                matched[k_stripped] = v
            else:
                unexpected.append(k)
        self.load_state_dict(matched, strict=False)
        print(f"  PointBERT weights loaded: {len(matched)} matched, "
              f"{len(model_state) - len(matched)} randomly init")

    def forward(self, voxels: torch.LongTensor) -> torch.Tensor:
        xyz, bids = self.voxel_to_pts(voxels)    # (B, M, 3), (B, M)
        b_feat    = self.block_embedding(bids)    # (B, M, block_embed_dim)
        x = torch.cat([xyz, b_feat], dim=-1)     # (B, M, 3+block_embed_dim)
        x = self.input_proj(x)                   # (B, M, trans_dim)
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)
        x = x.mean(dim=1)                        # (B, trans_dim) — global avg pool
        return self.output_head(x)

# ============================================================
#%% 🖼️ CELL 12 — TinyClip Text & Image Encoder
# ============================================================

class TinyClipTextEncoder(nn.Module):
    """
    TinyClip text encoder via HuggingFace CLIPModel.
    Output: (B, embed_dim) L2-normed embedding.
    """

    def __init__(self, cfg: dict, processor: CLIPProcessor):
        super().__init__()
        print(f"Loading TinyClip from {cfg['tinyclip_hf_model']} ...")
        clip = CLIPModel.from_pretrained(cfg["tinyclip_hf_model"])
        self.text_model  = clip.text_model
        self.text_proj   = clip.text_projection
        self.processor   = processor
        self.max_length  = min(cfg["text_max_length"], 77)

        # Freeze CLIP backbone
        if cfg["freeze_clip"]:
            for p in self.text_model.parameters():
                p.requires_grad = False
            for p in self.text_proj.parameters():
                p.requires_grad = False
            print("  TinyClip text: backbone FROZEN")

        clip_out_dim = clip.config.projection_dim  # e.g., 512 for TinyClip-39M
        self.proj = nn.Linear(clip_out_dim, cfg["embed_dim"])
        print(f"  TinyClip text proj: {clip_out_dim} → {cfg['embed_dim']}")

    def encode_text(self, texts: List[str]) -> torch.Tensor:
        device = next(self.parameters()).device
        inputs = self.processor(
            text=texts, padding=True, truncation=True,
            max_length=self.max_length, return_tensors="pt"
        ).to(device)
        out   = self.text_model(**inputs)
        # Use [CLS] pooled output
        feats = out.pooler_output                           # (B, hidden)
        feats = self.text_proj(feats)                      # (B, clip_out_dim)
        feats = self.proj(feats)                           # (B, embed_dim)
        return F.normalize(feats, dim=-1)

    def forward(self, texts: List[str]) -> torch.Tensor:
        return self.encode_text(texts)


class TinyClipImageEncoder(nn.Module):
    """
    TinyClip image encoder via HuggingFace CLIPModel.
    Output: (B, embed_dim) L2-normed embedding.
    """

    def __init__(self, cfg: dict):
        super().__init__()
        print(f"Loading TinyClip image encoder ...")
        clip = CLIPModel.from_pretrained(cfg["tinyclip_hf_model"])
        self.vision_model = clip.vision_model
        self.visual_proj  = clip.visual_projection

        if cfg["freeze_clip"]:
            for p in self.vision_model.parameters():
                p.requires_grad = False
            for p in self.visual_proj.parameters():
                p.requires_grad = False
            print("  TinyClip image: backbone FROZEN")

        clip_out_dim = clip.config.projection_dim
        self.proj = nn.Linear(clip_out_dim, cfg["embed_dim"])
        print(f"  TinyClip image proj: {clip_out_dim} → {cfg['embed_dim']}")

    def forward(self, pixel_values: torch.Tensor) -> torch.Tensor:
        out   = self.vision_model(pixel_values=pixel_values)
        feats = out.pooler_output                         # (B, hidden)
        feats = self.visual_proj(feats)                   # (B, clip_out_dim)
        feats = self.proj(feats)                          # (B, embed_dim)
        return F.normalize(feats, dim=-1)

# ============================================================
#%% 🔗 CELL 13 — TriModal Model
# ============================================================

class TriModalEncoder(nn.Module):
    """
    Unified tri-modal encoder.
    text  → 256-dim L2-normalized
    image → 256-dim L2-normalized
    voxel → 256-dim L2-normalized
    """

    def __init__(self, cfg: dict, vocab_size: int, processor: CLIPProcessor):
        super().__init__()
        self.text_encoder  = TinyClipTextEncoder(cfg, processor)
        self.image_encoder = TinyClipImageEncoder(cfg)
        self.voxel_encoder = PointBERTVoxelEncoder(cfg, vocab_size)

    def encode_text(self, texts: List[str]) -> torch.Tensor:
        return self.text_encoder(texts)

    def encode_image(self, pixel_values: torch.Tensor) -> torch.Tensor:
        return self.image_encoder(pixel_values)

    def encode_voxel(self, voxels: torch.LongTensor) -> torch.Tensor:
        out = self.voxel_encoder(voxels)
        return F.normalize(out, dim=-1)

    def forward(self, texts, pixel_values, voxels):
        t = self.encode_text(texts)
        i = self.encode_image(pixel_values)
        v = self.encode_voxel(voxels)
        return t, i, v

# ============================================================
#%% 🔥 CELL 14 — Tri-Modal InfoNCE Loss
# ============================================================

class TriModalCLIPLoss(nn.Module):
    """
    Symmetric InfoNCE loss pada 3 pasang modalitas:
      L = λ_TI * L(T,I) + λ_TV * L(T,V) + λ_IV * L(I,V)

    Masing-masing menggunakan satu learnable temperature (shared).
    """

    def __init__(self, temperature_init: float = 0.07,
                 lambda_ti: float = 1.0,
                 lambda_tv: float = 1.0,
                 lambda_iv: float = 1.0):
        super().__init__()
        self.temperature = nn.Parameter(torch.tensor(temperature_init).log())
        self.lambda_ti   = lambda_ti
        self.lambda_tv   = lambda_tv
        self.lambda_iv   = lambda_iv

    def _infonce(self, a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
        """Symmetric InfoNCE loss between two sets of embeddings."""
        tau     = self.temperature.exp().clamp(0.01, 10.0)
        logits  = (a @ b.T) / tau                              # (B, B)
        labels  = torch.arange(a.shape[0], device=a.device)
        loss_ab = F.cross_entropy(logits,   labels)
        loss_ba = F.cross_entropy(logits.T, labels)
        return (loss_ab + loss_ba) / 2.0

    def forward(self, text_emb: torch.Tensor,
                image_emb: torch.Tensor,
                voxel_emb: torch.Tensor) -> Tuple[torch.Tensor, Dict]:
        l_ti = self._infonce(text_emb, image_emb)
        l_tv = self._infonce(text_emb, voxel_emb)
        l_iv = self._infonce(image_emb, voxel_emb)

        total = self.lambda_ti * l_ti + self.lambda_tv * l_tv + self.lambda_iv * l_iv

        return total, {
            "loss_TI": l_ti.item(),
            "loss_TV": l_tv.item(),
            "loss_IV": l_iv.item(),
            "temperature": self.temperature.exp().item(),
        }

# ============================================================
#%% 📈 CELL 15 — Evaluation Metrics
# ============================================================

@torch.no_grad()
def extract_all_embeddings(model: TriModalEncoder, loader: DataLoader, device):
    """Extract text, image, voxel embeddings + categories dari seluruh split."""
    model.eval()
    text_embs, image_embs, voxel_embs = [], [], []
    all_categories = []

    for texts, images, voxels, categories in tqdm(loader, desc="Encoding", leave=False):
        images = images.to(device)
        voxels = voxels.to(device)

        t = model.encode_text(texts)
        i = model.encode_image(images)
        v = model.encode_voxel(voxels)

        text_embs.append(t.cpu())
        image_embs.append(i.cpu())
        voxel_embs.append(v.cpu())
        all_categories.extend(categories)

    return (torch.cat(text_embs),
            torch.cat(image_embs),
            torch.cat(voxel_embs),
            all_categories)


def compute_instance_metrics(query_embs: torch.Tensor,
                             gallery_embs: torch.Tensor,
                             ks: List[int] = [1, 5, 10]) -> Dict:
    """Recall@K, MRR, Median Rank, Mean Rank (query[i] matches gallery[i])."""
    sim = query_embs @ gallery_embs.T   # (N, N)
    N   = sim.shape[0]
    ranks = []
    for i in range(N):
        scores  = sim[i].clone()
        scores[i] -= 1e9                 # exclude self
        sorted_idx = scores.argsort(descending=True)
        rank = (sorted_idx == i).nonzero(as_tuple=False)[0].item() + 1
        ranks.append(rank)
    ranks = np.array(ranks)

    metrics = {}
    for k in ks:
        metrics[f"recall@{k}"] = float((ranks <= k).mean())
    metrics["mrr"]         = float((1.0 / ranks).mean())
    metrics["median_rank"] = float(np.median(ranks))
    metrics["mean_rank"]   = float(np.mean(ranks))
    return metrics


def compute_category_metrics(query_embs: torch.Tensor,
                             gallery_embs: torch.Tensor,
                             categories: List[str],
                             ks: List[int] = [1, 5, 10]) -> Dict:
    """Category-level precision@K and hit_rate@K."""
    sim = query_embs @ gallery_embs.T
    N   = sim.shape[0]
    cat_arr = np.array(categories)
    metrics = {}

    for k in ks:
        precisions, hit_rates = [], []
        for i in range(N):
            scores = sim[i].clone()
            scores[i] -= 1e9
            top_k_idx = scores.argsort(descending=True)[:k]
            top_k_cats = cat_arr[top_k_idx.numpy()]
            correct = (top_k_cats == cat_arr[i])
            precisions.append(correct.mean())
            hit_rates.append(float(correct.any()))
        metrics[f"cat_precision@{k}"] = float(np.mean(precisions))
        metrics[f"cat_hit_rate@{k}"]  = float(np.mean(hit_rates))

    return metrics


def evaluate(model: TriModalEncoder, loader: DataLoader,
             device, cfg: dict, split_name: str = "test"):
    """Full evaluation: instance + category metrics untuk semua pair."""
    t_embs, i_embs, v_embs, cats = extract_all_embeddings(model, loader, device)
    N = t_embs.shape[0]
    print(f"\n{'='*60}")
    print(f"  EVALUATION — {split_name.upper()} ({N} items)")
    print(f"{'='*60}")

    ks = cfg["recall_k"]
    results = {}

    for (q_name, g_name, q_embs, g_embs) in [
        ("Text",  "Voxel", t_embs, v_embs),
        ("Voxel", "Text",  v_embs, t_embs),
        ("Text",  "Image", t_embs, i_embs),
        ("Image", "Voxel", i_embs, v_embs),
    ]:
        inst = compute_instance_metrics(q_embs, g_embs, ks)
        cat  = compute_category_metrics(q_embs, g_embs, cats, ks)

        tag = f"{q_name}→{g_name}"
        results[tag] = {**inst, **cat}

        print(f"\n  📌 {tag} — Instance-Level:")
        for k in ks:
            print(f"     recall@{k:2d}: {inst[f'recall@{k}']:.4f}")
        print(f"     mrr        : {inst['mrr']:.4f}")
        print(f"     median_rank: {inst['median_rank']:.1f}")
        print(f"     mean_rank  : {inst['mean_rank']:.1f}")

        print(f"\n  📊 {tag} — Category-Level:")
        for k in ks:
            print(f"     cat_precision@{k}: {cat[f'cat_precision@{k}']:.4f}  "
                  f"cat_hit_rate@{k}: {cat[f'cat_hit_rate@{k}']:.4f}")

    return results

# ============================================================
#%% 🎛️ CELL 16 — Optimizer & Scheduler
# ============================================================

def build_optimizer_scheduler(model: TriModalEncoder,
                               criterion: TriModalCLIPLoss,
                               cfg: dict, num_training_steps: int):
    """Param groups dengan differential LR sesuai optimal P6."""

    # TinyClip text projection (trainable)
    text_proj_params = list(model.text_encoder.proj.parameters())

    # TinyClip image projection (trainable)
    img_proj_params = list(model.image_encoder.proj.parameters())

    # PointBERT adapter + head (selalu trainable)
    pb_adapter_params = (
        list(model.voxel_encoder.block_embedding.parameters()) +
        list(model.voxel_encoder.input_proj.parameters())
    )
    pb_head_params = list(model.voxel_encoder.output_head.parameters())

    # PointBERT backbone (unfreeze dengan lr sangat kecil)
    pb_backbone_params = (
        list(model.voxel_encoder.blocks.parameters()) +
        list(model.voxel_encoder.norm.parameters())
    )

    # Temperature
    temp_params = list(criterion.parameters())

    param_groups = [
        {"name": "text_proj",    "params": text_proj_params,    "lr": cfg["lr_text_proj"]},
        {"name": "image_proj",   "params": img_proj_params,     "lr": cfg["lr_image_proj"]},
        {"name": "pb_adapter",   "params": pb_adapter_params,   "lr": cfg["lr_pb_adapter"]},
        {"name": "pb_head",      "params": pb_head_params,      "lr": cfg["lr_pb_head"]},
        {"name": "pb_backbone",  "params": pb_backbone_params,  "lr": cfg["lr_pb_backbone"]},
        {"name": "temperature",  "params": temp_params,         "lr": cfg["lr_pb_adapter"]},
    ]

    optimizer = AdamW(param_groups, weight_decay=cfg["weight_decay"])

    # Warmup + Cosine annealing
    warmup_steps = int(num_training_steps * cfg["warmup_ratio"])
    warmup_sched  = LinearLR(optimizer, start_factor=0.1, end_factor=1.0,
                             total_iters=warmup_steps)
    cosine_sched  = CosineAnnealingLR(optimizer,
                                      T_max=num_training_steps - warmup_steps,
                                      eta_min=1e-7)
    scheduler = SequentialLR(optimizer, schedulers=[warmup_sched, cosine_sched],
                             milestones=[warmup_steps])

    # Print param groups
    print("\nOptimizer param groups:")
    for g in param_groups:
        n = sum(p.numel() for p in g["params"])
        print(f"  [{g['name']:15s}] lr={g['lr']:.1e}  params={n:,}")

    return optimizer, scheduler

# ============================================================
#%% 🏋️ CELL 17 — Training Loop
# ============================================================

def train_one_epoch(model, criterion, loader, optimizer, scheduler,
                    device, scaler, use_amp=True):
    model.train()
    criterion.train()
    total_loss = 0.0
    loss_breakdown = {"loss_TI": 0., "loss_TV": 0., "loss_IV": 0.}
    n = 0

    pbar = tqdm(loader, desc="  train", leave=False)
    for texts, images, voxels, _categories in pbar:
        images = images.to(device)
        voxels = voxels.to(device)

        optimizer.zero_grad()

        with autocast("cuda", enabled=use_amp):
            t, i, v = model(texts, images, voxels)
            loss, info = criterion(t, i, v)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        all_params = list(model.parameters()) + list(criterion.parameters())
        nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        total_loss += loss.item()
        for k in loss_breakdown:
            loss_breakdown[k] += info.get(k, 0.)
        n += 1
        pbar.set_postfix(
            loss=f"{loss.item():.4f}",
            τ=f"{info['temperature']:.3f}",
            TI=f"{info['loss_TI']:.3f}",
            TV=f"{info['loss_TV']:.3f}",
            IV=f"{info['loss_IV']:.3f}",
        )

    avg_loss = total_loss / max(n, 1)
    for k in loss_breakdown:
        loss_breakdown[k] /= max(n, 1)
    return avg_loss, loss_breakdown


@torch.no_grad()
def validate(model, criterion, loader, device, use_amp=True):
    model.eval()
    criterion.eval()
    total_loss = 0.0
    n = 0

    for texts, images, voxels, _categories in tqdm(loader, desc="  val  ", leave=False):
        images = images.to(device)
        voxels = voxels.to(device)
        with autocast("cuda", enabled=use_amp):
            t, i, v = model(texts, images, voxels)
            loss, _ = criterion(t, i, v)
        total_loss += loss.item()
        n += 1

    return total_loss / max(n, 1)


def save_checkpoint(path: str, model, criterion, optimizer, epoch: int,
                    best_val_loss: float, results: dict = None):
    torch.save({
        "epoch"         : epoch,
        "model_state"   : model.state_dict(),
        "criterion_state": criterion.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "best_val_loss" : best_val_loss,
        "results"       : results or {},
    }, path)

# ============================================================
#%% 🚀 CELL 18 — MAIN: Build Everything & Train
# ============================================================

def main():
    import random as pyrandom
    pyrandom.seed(CFG["seed"])
    np.random.seed(CFG["seed"])
    torch.manual_seed(CFG["seed"])
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(CFG["seed"])

    # ── Load Data ──────────────────────────────────────────────
    print("\n" + "="*60)
    print("  📂 Loading Dataset")
    print("="*60)
    train_loader, val_loader, test_loader, name2id, id2name, processor = \
        load_dataset_and_build_loaders(CFG)

    vocab_size = len(name2id)
    print(f"  Vocab size: {vocab_size}")
    print(f"  Train batches: {len(train_loader)}")

    # ── Build Model ────────────────────────────────────────────
    print("\n" + "="*60)
    print("  🧠 Building TriModal Model")
    print("="*60)
    model     = TriModalEncoder(CFG, vocab_size, processor).to(DEVICE)
    criterion = TriModalCLIPLoss(
        temperature_init=CFG["temperature_init"],
        lambda_ti=CFG["lambda_ti"],
        lambda_tv=CFG["lambda_tv"],
        lambda_iv=CFG["lambda_iv"],
    ).to(DEVICE)

    # Param count
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model.parameters())
    print(f"\n  Trainable: {trainable:,} / {total:,} params")

    # ── Semantic Init (Strategy 2) ─────────────────────────────
    if CFG["use_semantic_init"]:
        print("\n  Applying semantic block embedding init (Strategy 2) ...")
        with torch.no_grad():
            block_names = [id2name.get(i, "unknown block") for i in range(vocab_size)]
            # Encode block names dengan text encoder
            batch_size = 64
            all_embs = []
            for start in range(0, len(block_names), batch_size):
                chunk = block_names[start:start+batch_size]
                emb = model.encode_text(chunk).cpu()
                all_embs.append(emb)
            all_embs = torch.cat(all_embs, dim=0)           # (vocab, 256)

            # PCA down ke block_embed_dim (128)
            block_embed_dim = CFG["pb_block_embed_dim"]
            U, S, V = torch.pca_lowrank(all_embs, q=block_embed_dim)
            reduced = U * S
            reduced = reduced / (reduced.std() + 1e-8) * 0.1
            model.voxel_encoder.block_embedding.weight.data.copy_(
                reduced.to(DEVICE)
            )
        print("  ✅ Semantic init applied")

    # ── Optimizer & Scheduler ──────────────────────────────────
    steps_per_epoch    = len(train_loader)
    num_training_steps = CFG["epochs"] * steps_per_epoch

    optimizer, scheduler = build_optimizer_scheduler(
        model, criterion, CFG, num_training_steps
    )
    scaler = GradScaler(enabled=CFG["use_amp"])

    # ── Training Loop ──────────────────────────────────────────
    print("\n" + "="*60)
    print("  🏋️  Training")
    print("="*60)

    best_val_loss    = float("inf")
    patience_counter = 0
    history          = []

    for epoch in range(1, CFG["epochs"] + 1):
        t0 = time.time()

        train_loss, breakdown = train_one_epoch(
            model, criterion, train_loader, optimizer, scheduler,
            DEVICE, scaler, use_amp=CFG["use_amp"]
        )
        val_loss = validate(model, criterion, val_loader, DEVICE,
                            use_amp=CFG["use_amp"])

        elapsed = time.time() - t0
        print(f"  Epoch {epoch:03d}/{CFG['epochs']} | "
              f"train={train_loss:.4f} (TI={breakdown['loss_TI']:.3f} "
              f"TV={breakdown['loss_TV']:.3f} IV={breakdown['loss_IV']:.3f}) | "
              f"val={val_loss:.4f} | {elapsed:.1f}s")

        history.append({"epoch": epoch, "train": train_loss, "val": val_loss})

        # Checkpoint best model
        if val_loss < best_val_loss:
            best_val_loss    = val_loss
            patience_counter = 0
            save_checkpoint(
                os.path.join(CFG["checkpoint_dir"], "best_model.pth"),
                model, criterion, optimizer, epoch, best_val_loss
            )
            print(f"  ✅ Best model saved (val={best_val_loss:.4f})")
        else:
            patience_counter += 1
            if patience_counter >= CFG["early_stopping_patience"]:
                print(f"\n  ⏹️  Early stopping at epoch {epoch}")
                break

        # Periodic checkpoint
        if epoch % 10 == 0:
            save_checkpoint(
                os.path.join(CFG["checkpoint_dir"], f"epoch_{epoch:03d}.pth"),
                model, criterion, optimizer, epoch, best_val_loss
            )

    # ── Final Evaluation on Test Set ──────────────────────────
    print("\n" + "="*60)
    print("  📊 Final Evaluation on TEST SET")
    print("="*60)

    # Load best checkpoint
    best_ckpt = os.path.join(CFG["checkpoint_dir"], "best_model.pth")
    if os.path.exists(best_ckpt):
        ckpt = torch.load(best_ckpt, map_location=DEVICE, weights_only=False)
        model.load_state_dict(ckpt["model_state"])
        print(f"  Loaded best model from epoch {ckpt['epoch']}")

    test_results = evaluate(model, test_loader, DEVICE, CFG, split_name="test")

    # ── Save to Drive ──────────────────────────────────────────
    import shutil
    drive_save_dir = "/content/drive/MyDrive/mc-retrieval-trimodal"
    os.makedirs(drive_save_dir, exist_ok=True)
    shutil.copy(best_ckpt, os.path.join(drive_save_dir, "best_model.pth"))

    # Save results JSON
    import json
    with open(os.path.join(drive_save_dir, "test_results.json"), "w") as f:
        json.dump(test_results, f, indent=2)

    print(f"\n  ✅ Results saved to {drive_save_dir}")

    # ── Print Summary ──────────────────────────────────────────
    print("\n" + "="*60)
    print("  📋 RESULT SUMMARY")
    print("="*60)
    tv = test_results.get("Text→Voxel", {})
    print("  Text → Voxel (MAIN TASK):")
    for k in CFG["recall_k"]:
        print(f"    recall@{k:2d}    = {tv.get(f'recall@{k}', 0):.4f}")
    print(f"    mrr         = {tv.get('mrr', 0):.4f}")
    print(f"    median_rank = {tv.get('median_rank', 0):.1f}")
    print(f"    mean_rank   = {tv.get('mean_rank', 0):.1f}")

    for k in CFG["recall_k"]:
        print(f"    cat_hit@{k:2d}  = {tv.get(f'cat_hit_rate@{k}', 0):.4f}")

    # Bimodal baseline comparison
    print("\n  ─── vs. Bimodal Baseline (Percobaan 6) ───")
    bimodal = {"recall@1": 0.0768, "recall@5": 0.2161,
               "recall@10": 0.3337, "mrr": 0.1589, "median_rank": 22.0}
    for m, bv in bimodal.items():
        tv_v = tv.get(m, 0)
        delta = tv_v - bv
        sign  = "+" if delta >= 0 else ""
        print(f"    {m:12s}: {tv_v:.4f}  (Δ {sign}{delta:.4f} vs bimodal {bv:.4f})")

    return test_results

from google.colab import drive
drive.mount('/content/drive')

if __name__ == "__main__":
    results = main()

