# -*- coding: utf-8 -*-
"""fp-ir-trimodal-multiview-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1bhz9WPB-4WALlJMewFAEN7SMY8KQKX
"""

!git clone https://github.com/information-retrieval-4/mc-retrieval

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/mc-retrieval

!git checkout trimodal

# Commented out IPython magic to ensure Python compatibility.
# %pip install uv

!uv pip install -r requirements.txt

!git pull

!ls

!sudo apt install aria2

from google.colab import userdata

!aria2c -x 16 -s 16 -k 1M \
--http-user={userdata.get('KAGGLE_USERNAME')} \
--http-passwd={userdata.get('KAGGLE_KEY')} \
--continue=true \
--max-connection-per-server=16 \
--split=16 \
--min-split-size=10M \
-o sch-datasets.zip \
"https://www.kaggle.com/api/v1/datasets/download/farhanwew/minecraft-schematics-mvm"

!7z x sch-datasets.zip -aoa -odata/

!sed -i 's/batch_size: 128/batch_size: 512/g' configs/trimodal_tinyclip.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/mc-retrieval
!cat configs/trimodal_tinyclip.yaml

!python src/precompute_clip.py --config configs/trimodal_tinyclip.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/mc-retrieval
!python src/train.py --config configs/trimodal_tinyclip.yaml

!python src/evaluate.py --config configs/trimodal_tinyclip.yaml --checkpoint checkpoints/trimodal_tinyclip/best.pt

!python src/evaluate.py --config configs/trimodal_tinyclip.yaml --checkpoint checkpoints/trimodal_tinyclip/last.pt

from datetime import datetime

# Get current datetime and format it for the filename
current_time = datetime.now().strftime('%Y%m%d_%H%M%S')
zip_filename = f'checkpoints_{current_time}.zip'

# Remove any old zip files before creating a new one (optional, but good for cleanup)
!rm -f checkpoints_*.zip

# Create the zip archive with the datetime in its name
!zip -r {zip_filename} checkpoints/

!echo $zip_filename

# Run the curl command to upload the file to Catbox
print("Uploading to Fileditch...")
!curl -F "file=@{zip_filename}" https://new.fileditch.com/upload.php

print("\n\nUpload attempt finished.")